version: "3.9"

services:
  db:
    image: postgres:17
    container_name: taskmanager-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: collaborative-task-manager

    env_file:
      - .env

    depends_on:
      - db

    expose:
      - "8000"

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

volumes:
  postgres_data: